### ISSUE TITLE
ALB assigned with public nets instead of private

### ISSUE THREAD

**Issue by denisovval** [awslabs/sensitive-data-protection-on-aws#262]
When the admin stack is deployed with internal Alb, it chooses public nets instead of private ones.

### Reproduction Steps
1. Add public and private nets as parameters to admin stack
2. Choose AlbInternetFacing - No
3. Open internal ALB -> network mappings
4. See public subnets

### What did you expect to happen?

In network mapping for ALB there should be only private nets

### What actually happened?

Public nets are ssigned

### Environment

The latest version of the Admin stack (Version 1.0.0-4e8a780)

**Comment by nowfox** [comment]
You can use the following two templates. Please note that the private subnet requires a NAT Gateway.  
https://aws-gcr-solutions.s3.amazonaws.com/aws-sensitive-data-protection/latest/default/AdminOnlyPrivateSubnets.template.json  
https://aws-gcr-solutions.s3.amazonaws.com/aws-sensitive-data-protection/latest/default/AdminOnlyPrivateSubnetsWithIdP.template.json
